Repository mateusabelli/http-language-server, pull requests merged in 2023-04, with the labels that each got.

#5 Project refactor
  .github/FUNDING.yml
  .github/dependabot.yml
  .github/workflows/publish.yml
  .vscode/launch.json
  README.md
  package-lock.json
  package.json
  packages/client/LICENSE.md
  packages/client/README.md
  packages/client/extension.js
  packages/client/package.json
  packages/server/LICENSE.md
  packages/server/README.md
  packages/server/cli.js
  packages/server/package.json
  packages/server/src/docs/codes.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  scripts/package-lock.json
  scripts/package.json
  scripts/scraper.js
  src/cli.js
  src/docs/headers.json
  src/docs/methods.json
  src/docs/status.json
  src/providers/hoverProvider.js
  src/server.js
Labels: enhancement

#11 Revert refactoring
  .eslintignore
  .eslintrc.js
  .github/workflows/ci.yml
  .github/workflows/e2e.yml
  .github/workflows/npm.yml
  .gitignore
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  .vscodeignore
  client/package-lock.json
  client/package.json
  client/src/extension.ts
  client/src/test/completion.test.ts
  client/src/test/diagnostics.test.ts
  client/src/test/helper.ts
  client/src/test/index.ts
  client/src/test/runTest.ts
  client/testFixture/completion.txt
  client/testFixture/diagnostics.txt
  client/tsconfig.json
  package-lock.json
  package.json
  scripts/e2e.sh
  scripts/package-lock.json
  scripts/package.json
  scripts/scraper.js
  server/package-lock.json
  server/package.json
  server/src/server.ts
  server/src/tmp/cli.js
  server/src/tmp/docs/headers.json
  server/src/tmp/docs/methods.json
  server/src/tmp/docs/status.json
  server/src/tmp/providers/hover/index.js
  server/src/tmp/providers/hover/status.js
  server/tsconfig.json
  src/providers/diagnostics/.gitkeep
  src/server.js
  tsconfig.json
Labels: bug, documentation, enhancement

#17 Update workflows
  .github/workflows/ci.yml
  .github/workflows/e2e.yml
  .github/workflows/npm.yml
Labels: enhancement

#16 Syntax highlight
  package.json
  syntax/http.tmLanguage.json
  syntax/language-configuration.json
Labels: enhancement

#35 Issue28
  server/requirements.txt
Labels: enhancement, server

#36 Implement the CLI
  .vscode/launch.json
  client/src/extension.ts
  server/__main__.py
  server/server.py
Labels: enhancement, server

#37 Write README for Client and Server
  client/README.md
  server/README.md
Labels: documentation, client, server

#38 Improve README structure
  README.md
Labels: documentation

#41 Add CLI text to Server README
  server/README.md
Labels: documentation, server
